/*
 * rxtx_state_mashine.h
 *
 *  Created on: Apr 16, 2024
 *      Author: lepikhov
 */

#ifndef INC_COMMUNICATION_RXTX_STATE_MASHINE_H_
#define INC_COMMUNICATION_RXTX_STATE_MASHINE_H_

enum RXTX_STATE_MACHINE_STATES {
	RXTX_STATE_MACHINE_IDLE,
	RXTX_STATE_MACHINE_RECEIVING,
	RXTX_STATE_MACHINE_RECEIVED,
	RXTX_STATE_MACHINE_SENDING_GOOD_RESPONSE,
	RXTX_STATE_MACHINE_SENDING_ERROR_RESPONSE
};

enum RX_STATE_MACHINE_STATES {
	RX_STATE_MACHINE_WAITING_START_B,
	RX_STATE_MACHINE_WAITING_START_H,
	RX_STATE_MACHINE_RACEIVING_POCKET,
	RX_STATE_MACHINE_RACEIVED_B_IN_POCKET,
	RX_STATE_MACHINE_RACEIVED_FULL_POCKET,
	RX_STATE_MACHINE_RACEIVED_CRASHED_POCKET
};



#endif /* INC_COMMUNICATION_RXTX_STATE_MASHINE_H_ */
